formatter: markdown table
output:
  file: README.md
  mode: inject
sections:
  header: true
  inputs: true
  outputs: true
  providers: true
  resources: true
  modules: false
  requirements: false
  footer: false
