apiVersion: v2
name: externalSecrets
description: Umbrella Chart for external-secrets
type: application
version: 0.0.1
dependencies:
  - name: external-secrets
    repository: https://charts.external-secrets.io/
    version: 0.16.2  # https://artifacthub.io/packages/helm/external-secrets-operator/external-secrets