clusterSecretStores: {} # changeme
namespace: {}
external-secrets:
  replicaCount: 1
  certController:
    replicaCount: 1
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 100Mi
  webhook:
    replicaCount: 1
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 100Mi
  serviceMonitor:
    enabled: false
    additionalLabels:
      monitoring.instance: changeme
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      memory: 100Mi