apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-admin
  namespace: {{ .Values.namespaceName }}
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    name: "{{ .Values.rbac.groupName }}"
    apiGroup: rbac.authorization.k8s.io
