external-dns:
  tolerations:
    - key: "role"
      operator: "Equal"
      value: "infra"
      effect: "NoSchedule"
  domainFilters:
    - platformcon.stackit.run
  global:
    imagePullSecrets:
      - name: image-pull-secret
    security:
      allowInsecureImages: true
  provider:
    webhook:
      image:
        repository: ghcr.io/stackitcloud/external-dns-stackit-webhook
        tag: v0.3.2
  txtOwnerId: controlplane-production