clusterIssuer:
  name: changeme
  email: change@me
  server: change@me
cert-manager:
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      memory: 100Mi
  prometheus:
    servicemonitor:
      enabled: false
      labels:
        monitoring.instance: change
  installCRDs: true
  serviceAccount:
    automountServiceAccountToken: true
  webhook:
    timeoutSeconds: 15
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 100Mi
  cainjector:
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 100Mi
  startupapicheck:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 32Mi
namespace: {}
