argo-cd:
  dex:
    enabled: false
  redis:
    metrics:
      enabled: false
    serviceAccount:
      create: true
  controller:
    replicas: 1
  server:
    replicas: 1
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 90
  repoServer:
    replicas: 1
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 90
  applicationSet:
    replicas: 1
