apiVersion: v2
name: ingress-nginx
description: Umbrella Chart for ingress-nginx
type: application
version: 0.0.1
dependencies:
  - name: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
    version: 4.12.3