ingress-nginx:
  serviceAccount:
    automountServiceAccountToken: true
  controller:
    extraArgs:
      enable-ssl-passthrough: "true"
    kind: Deployment
    admissionWebhooks:
      certManager:
        enabled: true
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        memory: 1024Mi
    config:
      strict-validate-path-type: false

namespace: {}