apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster-project-y
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: vcluster-project-y
    server: "https://kubernetes.default.svc"
  sources:
    - repoURL: https://github.com/la-cc/workshop-platformcon-vcluster-gitops-idp.git
      targetRevision: main
      path: "./managed-service-catalog/helm/vcluster"
      helm:
        ignoreMissingValueFiles: true
        releaseName: "vcluster-project-y"
        valueFiles:
          - "values.yaml"
        values: |
          externalSecret:
            enabled: false
          namespaceName: vcluster-project-y
          rbac:
            groupName: "la-demos:g-gitops-2"
          vcluster:
            controlPlane:
              proxy:
                extraSANs:
                  - vcluster-project-y.platformcon.stackit.run
              ingress:
                enabled: true
                host: "vcluster-project-y.platformcon.stackit.run"
                pathType: ImplementationSpecific
                annotations:
                  nginx.ingress.kubernetes.io/backend-protocol: HTTPS
                  nginx.ingress.kubernetes.io/ssl-passthrough: "true"
                  nginx.ingress.kubernetes.io/ssl-redirect: "true"
                  cert-manager.io/cluster-issuer: letsencrypt-prod
                spec:
                  ingressClassName: nginx
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=false
      - PruneLast=true
      - FailOnSharedResource=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true